### ISSUE TITLE
Mantis Shrimp unable to Visualize geometry in Dynamo from GH Export

### ISSUE THREAD

**Issue by rkocourek** [ksobon/MantisShrimp#19] opened 2016-02-17 23:56 UTC
Using the GH export node in Dynamo I am unable to visualize the elements from Grasshopper. The data Is coming in correctly lists match in both grasshopper and Dynamo.

**Comment by ksobon** [comment] 2016-02-17 23:58
can you post more information? I can't answer this with no information to go on.

**Comment by rkocourek** [comment] 2016-02-18 00:11
Using Dynamo 0.9 version in Revit 2016, and Rhino 5 64 Bit with Grasshopper 0.90076 Version. In dynamo Mantis Shrimp (Current Package 10.27) node (Read GHFile) with file path from grasshopper (Grasshopper file exporting properly with (GH Export). Data list comes in to Dynamo DS Object output, however the elements do not show in the 3D preview of Dynamo navigator or inside of Revit. This is not a zoom issue. Not all other elements connects with Dynamo nodes will display properly.

![gh](https://cloud.githubusercontent.com/assets/17304619/13129305/01190f10-d591-11e5-9827-69a2ea2f044e.JPG)
![dynamo](https://cloud.githubusercontent.com/assets/17304619/13129306/011a277e-d591-11e5-8645-d5af06cf74ab.JPG)

**Comment by ksobon** [comment] 2016-02-18 00:13
it looks in dynamo that you are exporting strings. is that supposed to be a geometry? What's GLASS in grasshopper? Can i see that geometry?

**Comment by rkocourek** [comment] 2016-02-18 00:20
Well that's what I thought it might be at first, however I also tried to exporting a simple grid as shown in your example video and have been unsuccessful in visualizing that as well, but the data is coming thru and matching with GH.

![glass](https://cloud.githubusercontent.com/assets/17304619/13129480/231fc652-d592-11e5-8067-eb79281cf780.JPG)

**Comment by ksobon** [comment] 2016-02-18 01:17
Can you post that file?

**Comment by rkocourek** [comment] 2016-02-18 02:19
Try these, they are simple grids and they are not working. Exact replica of
your example video.

On Wed, Feb 17, 2016 at 5:17 PM, Konrad K Sobon <notifications@github.com>
wrote:

> Can you post that file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ksobon/MantisShrimp/issues/19#issuecomment-185493416>.
>



-- 
Ryan Kocourek

**Comment by ksobon** [comment] 2016-02-18 04:05
Again, can you post a sample Rhino model? I don't have a problem with my sample files. They are working just fine. I am trying to help you.

**Comment by rkocourek** [comment] 2016-02-18 05:11
Here is the rhino file, but that is not the issue. I'm sure it is a graphic
issue within Dynamo. All the nodes are working properly, data is flowing
from grasshopper to dynamo it just won't display. I believe there are other
people having the same issue. Which version of Mantis are you running,
there are several versions available thru Dynamo package, I have been
trying them all. Also which version of Revit and Dynamo are you using? I am
in Revit 2016 and Dynamo 0.9.

Thanks,

On Wed, Feb 17, 2016 at 8:05 PM, Konrad K Sobon <notifications@github.com>
wrote:

> Again, can you post a sample Rhino model? I don't have a problem with my
> sample files. They are working just fine. I am trying to help you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ksobon/MantisShrimp/issues/19#issuecomment-185534020>.
>



-- 
Ryan Kocourek

**Comment by ksobon** [comment] 2016-02-18 14:37
OK, in this case I will close this issue. I am running Revit 2016, Dynamo 0.9.1 Release Candidate, Rhino 5 x64 and Grasshopper 0.90076. Please post this issue to Dynamo forum or Dynamo GitHub page.

**Closed by ksobon** 2016-02-18 14:37 UTC
Labels: help wanted

**Comment by rkocourek** [comment] 2016-02-18 17:21
This doesn't solve the issue. The problem is still the Mantis Shrimp plugin, there is no issue importing any other geometry with other packages. Which version of Mantis Shrimp are you running?

Thanks

**Comment by ksobon** [comment] 2016-02-18 17:27
in your previous comment you stated: "i am sure it is a graphic issue within Dynamo" as well as "all the nodes are working properly". How is this a Mantis Shrimp issue? You are not getting any errors and as you stated, data/geometry is transferring properly. The problem is lack of preview in Watch 3D node, and that's not a Mantis Shrimp issue, but a Dynamo/graphics card issue. Again, please post to Dynamo git hub page.

**Comment by rkocourek** [comment] 2016-02-19 01:57
Konrad,

There is definitely an issue with the current Mantis Shrimp working with
Dynamo 0.9, 0.91 and 1.0 in Revit 2016. I have tried all of the import
nodes for both grasshopper and Rhino and receive the same result, no visual
data. I have tried this on six different machines and have adjusted all of
the graphic control features available. I think I will have to use another
option for my current project. I would be good to look into I'm sure this
is a common issue. If you have an example file you can send me to try that
would be great. I assume you are using the current Mantis Shrimp 10.27?

Thanks

On Thu, Feb 18, 2016 at 9:27 AM, Konrad K Sobon <notifications@github.com>
wrote:

> in your previous comment you stated: "i am sure it is a graphic issue
> within Dynamo" as well as "all the nodes are working properly". How is this
> a Mantis Shrimp issue? You are not getting any errors and as you stated,
> data/geometry is transferring properly. The problem is lack of preview in
> Watch 3D node, and that's not a Mantis Shrimp issue, but a Dynamo/graphics
> card issue. Again, please post to Dynamo git hub page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ksobon/MantisShrimp/issues/19#issuecomment-185825454>.
>



-- 
Ryan Kocourek
